DROP TABLE `events`;
DROP TABLE `event_plans`;
DROP TABLE `schedules`;
DROP TABLE `event_templates`;
DROP TABLE `user_roles`;
DROP TABLE `roles`;
DROP TABLE `sessions`;
DROP TABLE `passwords`;
DROP TABLE `users`;
